# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `open_uri_redirections` gem.
# Please instead update this file by running `bin/tapioca gem open_uri_redirections`.


# Patch to allow open-uri to follow safe (http to https) and unsafe redirections (https to http).
# Original gist URL:
# https://gist.github.com/1271420
#
# Relevant issue:
# http://redmine.ruby-lang.org/issues/3719
#
# Source here:
# https://github.com/ruby/ruby/blob/trunk/lib/open-uri.rb
#
# Thread-safe implementation adapted from:
# https://github.com/obfusk/open_uri_w_redirect_to_https
#
# source://open_uri_redirections//lib/open-uri/redirections_patch.rb#14
module OpenURI
  class << self
    # OpenURI::open can receive different kinds of arguments, like a string for the mode
    # or an integer for the permissions, and then a hash with options like UserAgent, etc.
    #
    # This method helps us find this options hash, as it is where our :allow_redirections
    # option will reside.
    #
    # source://open_uri_redirections//lib/open-uri/redirections_patch.rb#68
    def first_hash_argument(arguments); end

    # Patches the original open_uri method to accept the :allow_redirections option
    #
    # :allow_redirections => :safe will allow HTTP => HTTPS redirections.
    # :allow_redirections => :all  will allow HTTP => HTTPS and HTTPS => HTTP redirections.
    #
    # source://open_uri_redirections//lib/open-uri/redirections_patch.rb#44
    def open_uri(name, *rest, &block); end

    # source://open_uri_redirections//lib/open-uri/redirections_patch.rb#16
    def open_uri_original(name, *rest); end

    # @return [Boolean]
    #
    # source://open_uri_redirections//lib/open-uri/redirections_patch.rb#19
    def redirectable?(uri1, uri2); end

    # @return [Boolean]
    #
    # source://open_uri_redirections//lib/open-uri/redirections_patch.rb#34
    def redirectable_all?(uri1, uri2); end

    # source://open_uri_redirections//lib/open-uri/redirections_patch.rb#17
    def redirectable_cautious?(uri1, uri2); end

    # @return [Boolean]
    #
    # source://open_uri_redirections//lib/open-uri/redirections_patch.rb#30
    def redirectable_safe?(uri1, uri2); end
  end
end
