#!/usr/bin/env ruby

require 'simple_scripting/argv'
require 'simple_scripting/configuration'

require 'open3'
require 'io/wait'
require 'shellwords'

class ApplicationConfiguration
  def load_arguments_and_configuration
    master_device, slave_devices = load_and_check_devices_configuration

    long_help = <<~HELP
      Connect an audio BT device (referred as "slave") to the system (referred as "master").

      Besides providing a mean to perform the operation, the script helps the user working around the extremely annoying issues with the steaming pile of trash that are Bluetooth, Bluez, and the Ubuntu BT support.

      The combination of the above is very unreliable, and repeated attempts are often necessary to connect devices.
      In addition, Ubuntu has shipped a broken stack in any version, including any LTS. A specific workaround is provided for working around a bug in Ubuntu 16.04.

      The script will preserve the Bluetooth master devices status, so if BT is disabled, the script will enable it, and disable it on exit.

      Switches:

      <device>: Prefix of the slave device name to connect.

      Configured slave devices: #{slave_devices.keys.map { |name| name + (name == slave_devices.keys.first ? " (default)" : "") }.join(', ')}

      Configuration:

      The configuration file ("$HOME/.connect_bt_device") has the following structure:

      ```
      [master]
      master_device = <rfkill_device>

      [slaves]
      <device_name_1> = <device_id_1>
      <device_name_2> = <device_id_2>
      ...
      ```

      The first line in the [slaves] group is the default device.
      The [master] group is optional; the master device is the `DEVICE` entry of the `rfkill` command.
    HELP

    options = SimpleScripting::Argv.decode(
      [ '-a', '--reset-a2dp-profile',   'Reset the A2DP profile (Ubuntu 16.04 workaround)' ],
      '[device]',
      long_help: long_help
    ) || exit

    slave_device_id = find_slave_device_id(slave_devices, options[:device])

    [master_device, slave_device_id, !!options[:reset_a2dp_profile]]
  end

  private

  # Returns [slave_devices (Hash), master_device].
  #
  def load_and_check_devices_configuration
    configuration = SimpleScripting::Configuration.load

    if configuration['slaves'].to_h.empty?
      raise "No slave devices configured!"
    else
      master_device = configuration['master']&.master_device
      slave_devices = configuration['slaves'].to_h.map { |name, id| [name.to_s, id] }.to_h

      [master_device, slave_devices]
    end
  end

  def find_slave_device_id(slave_devices, device_prefix)
    if device_prefix
      # simplified algorithm
      matching_devices = slave_devices.select { |name, _| name.start_with?(device_prefix) }

      case matching_devices.size
      when 0
        raise "No matching devices found!"
      when 1
        matching_devices.values.first
      when 2
        raise "Multiple devices found: #{matching_devices.map(&:first)}"
      end
    else
      slave_devices.values.first
    end
  end
end # ApplicationConfiguration

module BluetoothDevicesConnectionHelper
  def connect_audio_slave_device(slave_device_id, pa_card_name, reset_a2dp_profile: false)
    with_bluetooth_ctl do |stdin, stdout|
      connect_slave_device_loop(slave_device_id, stdin, stdout)

      if reset_a2dp_profile
        set_pa_card_profile(pa_card_name, 'off')

        disconnect_slave_device_loop(slave_device_id, stdin, stdout)
        connect_slave_device_loop(slave_device_id, stdin, stdout)

        set_pa_card_profile(pa_card_name, 'a2dp_sink')
      end
    end
  end

  def disconnect_slave_device(slave_device_id)
    with_bluetooth_ctl do |stdin, stdout|
      disconnect_slave_device_loop(slave_device_id, stdin, stdout) if slave_device_connected?(slave_device_id, stdin, stdout)
    end
  end

  private

  # :readline will block if there is no input available, while :readX will raise an error; in order
  # to solve this problem easily, the 'io/wait' library makes `IO#ready?` available.
  #
  # params:
  #   wait_pattern: keep reading until the expected pattern is found
  #   timeout: in seconds; used only when :wait_pattern is specified
  #
  #
  def read_available_io(io, wait_pattern: nil, timeout: 1)
    buffer = ''
    start_time = Time.now.to_f

    while true
      buffer << io.readchar while io.ready?

      if wait_pattern
        if buffer =~ wait_pattern
          break
        elsif timeout && Time.now.to_f >= start_time + timeout
          raise "Timout while waiting for pattern #{wait_pattern} not found; current buffer: #{buffer}"
        else
          sleep 0.1
        end
      else
        break
      end
    end

    buffer
  end

  def with_bluetooth_ctl(&block)
    Open3.popen3('bluetoothctl') do |stdin, stdout, _, _|
      puts read_available_io(stdout, wait_pattern: /^Agent registered/)

      yield(stdin, stdout)
    end
  end

  def connect_slave_device_loop(slave_device_id, bt_ctl_in, bt_ctl_out)
    loop do
      bt_ctl_in.puts("connect #{slave_device_id}")

      while true
        output = read_available_io(bt_ctl_out)

        puts output if output != ''

        case output
        when /Connection successful/
          puts
          return
        when /Failed to connect/
          break
        else
          sleep 0.5
        end
      end
    end
  end # connect_slave_device_loop

  def set_pa_card_profile(card, profile)
    puts "Setting PA card profile: #{profile}"

    Open3.popen3("pactl set-card-profile #{card} #{profile}") do |_, _, stderr, wait_thread|
      if ! wait_thread.value.success?
        puts stderr.readlines.join
        exit
      end
    end

    puts
  end

  def slave_device_connected?(slave_device_id, bt_ctl_in, bt_ctl_out)
    bt_ctl_in.puts("info #{slave_device_id}")

    device_information = read_available_io(bt_ctl_out, wait_pattern: /^\s+Connected: \w+$/)

    device_information =~ /^\s+Connected: yes$/
  end

  def disconnect_slave_device_loop(slave_device_id, bt_ctl_in, bt_ctl_out)
    puts "Starting disconnect slave loop..."

    loop do
      bt_ctl_in.puts("disconnect #{slave_device_id}")

      while true
        output = read_available_io(bt_ctl_out)

        puts output if output != ''

        # Disconnection will always be successful, when the device is available.
        #
        case output
        when /Successful disconnected/
          puts
          return
        when /(Device [0-9A-F:] not available)/
          raise $1
        else
          sleep 0.5
        end
      end
    end
  end # :disconnect_slave_device_loop
end # BluetoothDevicesConnectionHelper

# In this context, `device` refers to the master device(s).
#
class BluetoothStateManager
  DEVICE_BLOCKED = 'blocked'

  include BluetoothDevicesConnectionHelper

  def initialize
    @initiated_disconnect_slave = false
    @initiated_disable_master = false
  end

  def with_bluetooth_enabled(device: nil)
    device_start_statuses = find_device_statuses(only: device)

    check_device_statuses!(device_start_statuses) unless device

    enable_devices(device_start_statuses) if devices_blocked?(device_start_statuses)

    slave_device_id = nil

    trap("INT") do
      puts "Interrupt captured; initiating manual exit..."

      if !@initiated_disconnect_slave
        @initiated_disconnect_slave = true
        disconnect_slave_device(slave_device_id) if slave_device_id
      end

      if !@initiated_disable_master
        @initiated_disable_master = true
        disable_devices(device_start_statuses)
      end

      raise Interrupt
    end

    slave_device_id = yield

    if devices_blocked?(device_start_statuses)
      pause

      disconnect_slave_device(slave_device_id)

      disable_devices(device_start_statuses)
    end
  end

  private

  # Returns an array of Struct(id, device, blocked).
  #
  #   [id, "device", status (boolean)]
  #
  def find_device_statuses(only: device)
    devices_data = `rfkill`.scan(/^ *(\d+) bluetooth (\w+) +(\w+)/)

    devices_data = devices_data.select { |_, device, _| device == only } if only

    if devices_data.empty?
      if only
        raise "Device #{only.inspect} not found!"
      else
        raise "No master devices found!"
      end
    else
      devices_data.map do |raw_id, device, raw_status|
        Struct.new(:id, :device, :blocked).new(
          raw_id.to_i,
          device,
          raw_status == DEVICE_BLOCKED,
        )
      end
    end
  end

  # Allow only all blocked or all unblocked.
  #
  def check_device_statuses!(device_statuses)
    if device_statuses.map(&:blocked).uniq.size != 1
      raise "Mixed statuses found: " + device_statuses.map { |device_status| [device_status.device, device_status.blocked] }.to_h.to_s
    end
  end

  def devices_blocked?(device_statuses)
    device_statuses.map(&:blocked).uniq == [true]
  end

  def enable_devices(device_statuses)
    puts "Enabling #{device_statuses.map(&:device).join(', ')}...", ""

    device_statuses.each do |device|
      `rfkill unblock #{device.id}`
    end
  end

  def pause
    print 'Press Enter to disable the master devices and exit...'
    gets
  end

  def disable_devices(device_statuses)
    puts "Disabling #{device_statuses.map(&:device).join(', ')}...", ""

    device_statuses.each do |device|
      `rfkill block #{device.id}`
    end
  end
end # BluetoothStateManager

class BluetoothDevicesConnectionManager
  include BluetoothDevicesConnectionHelper

  # Returns the device id (mostly, for convenience).
  #
  def connect(slave_device_id, reset_a2dp_profile: false)
    bluez_pa_card_name = generate_bluez_pa_card_name(slave_device_id)

    connect_audio_slave_device(slave_device_id, bluez_pa_card_name, reset_a2dp_profile: reset_a2dp_profile)

    slave_device_id
  end

  private

  # Example:
  #
  #   00:1B:66:7F:E6:F3 -> bluez_card.00_1B_66_7F_E6_F3
  #
  # Names can be manually found via `pactl list cards`.
  #
  def generate_bluez_pa_card_name(slave_device_id)
    "bluez_card." + slave_device_id.gsub(':', '_')
  end
end

if __FILE__ == $PROGRAM_NAME
  master_device, slave_device_id, reset_a2dp_profile = ApplicationConfiguration.new.load_arguments_and_configuration

  BluetoothStateManager.new.with_bluetooth_enabled(device: master_device) do
    BluetoothDevicesConnectionManager.new.connect(slave_device_id, reset_a2dp_profile: reset_a2dp_profile)
  end
end
