#!/usr/bin/env bash

set -o pipefail
set -o errexit
set -o nounset
set -o errtrace
shopt -s inherit_errexit

c_help="Usage: $(basename "$0") [-h|--help] [-u|--user <user>] [-b|--binary <binary>] <operation> <operation_params...>

- Start the snap services
- Executes the operation (run, install, remove...) on the specified snap
- Stop the snap services

Doesn't support invocations from the desktop environment; only from terminal.

For systems where the snap binary has been overwritten, it's possible to use the '--binary' option, or set \$DESNAPPED_SNAP_BINARY.

The parameters '--invoking-user' should not be manually passed (it's used when switching to sudo)."

v_invoking_user=
v_snap_binary=${DESNAPPED_SNAP_BINARY:-$(which snap)}
v_operation=
v_operation_params=()

function decode_cmdline_args {
  local params
  params=$(getopt --options hu:b: --long help,user:,binary: --name "$(basename "$0")" -- "$@")

  eval set -- "$params"

  while true; do
    case $1 in
      -h|--help)
        echo "$c_help"
        exit 0 ;;
      -u|--user)
        v_invoking_user=$2
        shift 2 ;;
      -b|--binary)
        v_snap_binary=$2
        shift 2 ;;
      --)
        shift
        break ;;
    esac
  done

  if [[ $# -lt 1 ]]; then
    echo "$c_help"
    exit 1
  fi

  v_operation=$1
  v_operation_params+=("${@:2}")
}

function prepare_sudo {
  if [[ $(id -u) -ne 0 ]]; then
    sudo "$0" --user "$(whoami)" --binary "$v_snap_binary" "$@"
    exit $?
  fi
}

function start_snapd_units {
  systemctl start snapd.apparmor snapd
}

function execute_snap_operation {
  sudo -u "$v_invoking_user" "$v_snap_binary" "$v_operation" "${v_operation_params[@]}"
}

function stop_snapd_units {
  systemctl stop snapd{,.socket,.seeded,.snap-repair.timer,.apparmor}
}

decode_cmdline_args "$@"
prepare_sudo "$@"
start_snapd_units
execute_snap_operation
stop_snapd_units
