#!/bin/bash

set -o errexit

if [[ "$#" != 0 ]]; then
  echo 'Usage: git_purge_empty_branches'
  echo
  echo "Delete all the branches (local, and their remote tracked) that haven't any commits that aren't in master."
  echo "Can be run from any branch, but requires a clean tree."
  echo
  echo $'It won\'t delete any branch named `master` or `deployment`'

  exit 0
fi

if [[ $(git status | grep "nothing to commit, working tree clean") == "" ]]; then
  echo 'Please commit/stash any change before proceeding!'
  exit 1
fi

# Fetch all, so that this script can be generally used for syncing the repo.
git fetch --all --tags --prune

git checkout master > /dev/null 2>&1

git rebase

for branch in $(git branch | cut -c 3- | egrep -v '^(master|deployment)$'); do
  if [[ ! $(git cherry master $branch | grep '^+') ]]; then
    git branch -D $branch

    if git branch -r | grep "origin/$branch\$"; then
      git push origin :$branch
    fi
  fi
done

# Will fail if the user was on a now deleted branch, but doesn't really matter.
git checkout - > /dev/null 2>&1
