#!/bin/bash

set -o pipefail
set -o errexit
set -o nounset

help="\
Usage: $(basename "$0") [-h|--help] <url> [<custom_name>]

Generates a git.io URL, and copies it to the clipboard (with the protocol stripped).

Requires xsel.

Vanity URLs are not supported, since it seems they've been discontinued (the parameter is ignored).
"

v_source_url=

function decode_cmdline_arguments {
  eval set -- "$(getopt --options h --long help -- "$@")"

  while true; do
    case "$1" in
      -h|--help)
        echo "$help"
        exit 0 ;;
      --)
        shift
        break ;;
    esac
  done

  if (($# != 1)); then
    echo "$help"
    exit 1
  fi

  v_source_url=$1
}

function generate_url {
  local response=$(curl -si https://git.io -F "url=$v_source_url")

  if [[ $response =~ 422 ]]; then
    echo "$response" | grep '^Status: '
  else
    echo "${response/https:\/\//}" | perl -ne '/^Location: (\S+)/ && print $1' | tee >(xsel -ib)
  fi
}

decode_cmdline_arguments "$@"
generate_url
