#!/bin/bash

set -o pipefail
set -o errexit
set -o nounset
set -o errtrace
shopt -s inherit_errexit

help="\
Usage: $(basename "$0") [-h|--help] <url>

Generates a git.io URL, and copies it to the clipboard (with the protocol stripped).

Requires xsel.

Vanity URLs are not supported, since it seems they've been discontinued.
"

v_source_url=

function decode_cmdline_arguments {
  local params
  params=$(getopt --options h --long help --name "$(basename "$0")" -- "$@")

  eval set -- "$params"

  while true; do
    case "$1" in
      -h|--help)
        echo "$help"
        exit 0 ;;
      --)
        shift
        break ;;
    esac
  done

  if (($# != 1)); then
    echo "$help"
    exit 1
  fi

  v_source_url=$1
}

function generate_url {
  local response=
  response=$(curl -si https://git.io -F "url=$v_source_url")

  if [[ $response =~ 422 ]]; then
    echo "$response" | grep '^Status: '
  else
    echo "${response/https:\/\//}" | perl -ne '/^Location: (\S+)/ && print $1' | tee >(xsel -ib)
  fi
}

decode_cmdline_arguments "$@"
generate_url
