#!/bin/bash

# Run the last query, and copy the result to the clipboard (in table format).
#
# Requires `general_log = ON` and `log_output = TABLE` server settings.
#
# For simplicity, it relies on the assumption that each connection has a new thread id; without
# this, a `USE` invocation from a previous connection with the same thread id would be
# inappropriately executed.
# For dev environments, this logic is good enough and not worth the extra complexity to handle the
# case above.
#
# Regardless, this approach is obviously not suited for non-deterministic functions, e.g. RAND().
#
# Note that batch mode (`--batch`) queries are still logged, so we need to handle this.

# Used in the EXPLAIN test.
#
shopt -s nocasematch

# In tab-separated mode (not to confuse with table format), the output newlines are escaped, so we
# unescape them (via sed).

query_thread_id=$(mysql -se "SELECT thread_id FROM mysql.general_log WHERE command_type = 'Query' AND thread_id != CONNECTION_ID()" | tail -n 1)

query=$(mysql -se "SELECT argument FROM mysql.general_log WHERE command_type = 'Query' AND thread_id = $query_thread_id" | tail -n 1 | sed 's/\\n/\n/g')
query_used_db=$(mysql -se "SELECT argument FROM mysql.general_log WHERE command_type = 'Init DB' AND thread_id = $query_thread_id" | tail -n 1)

# The \G modifier is a MySQL client functionality, not stored in the general log. For this reason,
# we manually don't use table ouput in some cases
#
# `-N` removes the result header.
#
# If the number of `\G` cases increase, a hash table can be comfortably used.
#
case "$query" in
  "EXPLAIN FORMAT="*)
    query_output_formatting='s/\\n/\n/g'
    output_option="-N"
    ;;
  "SHOW CREATE TABLE"*)
    # Remove the table name from the first result line.
    #
    query_output_formatting='1 s/.*\t//; s/\\n/\n/g'
    output_option="-N"
    ;;
  *)
    query_output_formatting=''
    output_option="-t"
  ;;
esac

if [[ $query_used_db != "" ]]; then
  query="USE $query_used_db; $query"
fi

echo "# Query ##########################"
echo "$query"
echo "##################################"

mysql $output_option -e "$query" | sed "$query_output_formatting" | tee >(xsel -ib)
