#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

c_help="Usage: mystop [-h|--help]

Companion of 'mystart': stops the running 'mysqld' process, and removes the directories.

See 'mystart' for informations about the workflow."

function decode_cmdline_args {
  if [[ $# -ne 0 ]]; then
    echo "$c_help"

    if [[ "$1" == "-h" || "$1" == "--help" ]]; then
      exit 0
    else
      exit 1
    fi
  fi
}

function kill_mysqld {
  if pkill --exact mysqld; then
    while pgrep --exact mysqld > /dev/null; do
      sleep 0.1
    done
  fi
}

function delete_directories {
  local data_location
  data_location=$(my_print_defaults mysqld | perl -ne 'print $1 if /^--datadir=(.+)'/)

  if [[ -z $data_location ]]; then
    echo "Error: Could not determine the data directory locations."
    exit 1
  fi

  echo "Removing data dir: $data_location..."
  rm -rf "$data_location"

  local logs_location
  logs_location=$(my_print_defaults mysqld | perl -ne 'print $1 if /^--innodb_log_group_home_dir=(.+)'/)

  # Can be empty; if so, the data dir is used, so no handling is needed.
  #
  if [[ -n $logs_location ]]; then
    echo "Removing logs dir: $logs_location..."
    rm -rf "$logs_location"
  fi
}

decode_cmdline_args "$@"
kill_mysqld
delete_directories
