#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

c_help='Usage: mystop [-h|--help]

Companion of `mystart`: stops the running `mysqld` process, and removes the directories.

See `mystart` for informations about the workflow.'

if [[ $# -ne 0 ]]; then
  echo "$c_help"

  if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    exit 0
  else
    exit 1
  fi
fi

if pkill mysqld; then
  while pgrep mysqld > /dev/null; do 
    sleep 0.1
  done
fi

rm -rf "$MYSTART_LOGS_LOCATION" "$MYSTART_DATA_LOCATION"
