#!/usr/bin/env bash

set -o pipefail
set -o errexit
set -o nounset
set -o errtrace
shopt -s inherit_errexit

c_help="Usage: $(basename "$0") [-h|--help] <cue_file> <v_audio_file>

Splits the audio file and converts it to flac.
"

v_cue_file=
v_audio_file=

function decode_cmdline_args {
  local params
  params=$(getopt --options h --long help --name "$(basename "$0")" -- "$@")

  eval set -- "$params"

  while true; do
    case $1 in
      -h|--help)
        echo "$c_help"
        exit 0 ;;
      --)
        shift
        break ;;
    esac
  done

  if [[ $# -ne 2 ]]; then
    echo "$c_help"
    exit 1
  fi

  v_cue_file=$1
  v_audio_file=$2
}

function main {
  shnsplit -t "%n - %t" -o "flac flac --replay-gain --best -o %f -" -f "$v_cue_file" "$v_audio_file"
}

decode_cmdline_args "$@"
main
