#!/usr/bin/env ruby

require_relative 'kernel_packages_maintenance/kernel_version'
load "#{__dir__}/clean_kernel_packages"

require 'simple_scripting/argv'

require 'open-uri'
require 'ostruct'
require 'ruby-progressbar'
require 'uri'

class DownloadWithProgress

  def execute(address, destination_file)
    uri = URI(address)

    Net::HTTP.start(uri.host) do |http|
      response = http.request_head(address)

      file_basename = File.basename(destination_file)
      file_size = response['content-length'].to_i

      progress_bar = ProgressBar.create(title: "  #{file_basename}", total: file_size)

      File.open(destination_file, "wb") do |file|
        http.get(address) do |data_chunk|
          file << data_chunk
          progress_bar.progress += data_chunk.length
        end
      end

      progress_bar.finish
    end
  end

end

class UpdateMainlineKernel

  PPA_ADDRESS = "http://kernel.ubuntu.com/~kernel-ppa/mainline"
  KERNEL_TYPE = "generic"
  ARCHITECTURE = "amd64"
  DEFAULT_STORE_PATH = '/tmp'

  def execute(install: nil, store_path: DEFAULT_STORE_PATH)
    case install
    when nil
      current_version = KernelVersion.find_current
      install_latest_kernel_for_current_version(current_version, store_path)
    when /^(\d+)\.(\d+)$/
      # Simulate the system having the earliest version (rc0, not existing) of the specified
      # version.
      select_version_rc0 = KernelVersion.new($1, $2, 0, rc: 0)
      install_latest_kernel_for_current_version(select_version_rc0, store_path)
    when /^(\d+)\.(\d+)\.(\d+)$/
      specific_version = KernelVersion.new($1, $2, $3)
      install_specific_version(specific_version, store_path)
    else
      raise "Unexpected_version: #{install}"
    end
  end

  private

  def install_latest_kernel_for_current_version(current_version, store_path)
    puts "Current kernel version: #{current_version}"

    mainline_ppa_page = load_mainline_ppa_page

    all_patch_versions = find_all_patch_versions_for_kernel_version(mainline_ppa_page, current_version)

    puts "Latest version: #{all_patch_versions.sort.last}"

    installable_versions = all_patch_versions.select { |version| version > current_version }

    if installable_versions.size > 0
      any_version_installed = install_latest_possible_version(installable_versions, store_path)
      CleanKernelPackages.new.execute if any_version_installed
    else
      puts "Nothing to do."
    end
  end

  def install_specific_version(version, store_path)
    mainline_ppa_page = load_mainline_ppa_page

    version_installed = install_version(version, store_path)

    CleanKernelPackages.new.execute if version_installed
  end

  def load_mainline_ppa_page
    open(PPA_ADDRESS).read
  end

  def find_all_patch_versions_for_kernel_version(mainline_ppa_page, version)
    # Examples (from 4.8+; previous rc versions also had suffixes):
    #
    #     href="v4.9.7/"
    #     href="v4.10-rc6/"
    #
    matching_links_found = mainline_ppa_page.scan(%r{href="v#{version.major}\.#{version.minor}(\.(\d+))?(-rc(\d+))?/"})

    matching_links_found.map do |_, patch, _, rc|
      KernelVersion.new(version.major, version.minor, patch, rc: rc)
    end
  end

  # Tries to install the latest of the passed versions.
  # Returns true if any kernel was installed; false otherwise.
  #
  def install_latest_possible_version(installable_versions, store_path)
    installable_versions.sort.reverse.each do |installable_version|
      version_installed = install_version(installable_version, store_path)

      return true if version_installed
    end

    return false
  end

  def install_version(version, store_path)
    puts "Version: #{version}"

    puts "- finding package addresses..."

    package_addresses = find_kernel_package_addresses(version)

    puts "- downloading packages..."

    package_files = download_package_files(package_addresses, store_path)

    if package_files.empty?
      puts "- build failed! skipping..."

      return false
    else
      puts "- installing packages..."

      install_packages(package_files)

      return true
    end
  end

  def find_kernel_package_addresses(version)
    kernel_page_address = "#{PPA_ADDRESS}/v#{version.major}.#{version.minor}"

    if version.rc
      kernel_page_address << "-rc#{version.rc}"
    elsif version.patch > 0
      kernel_page_address << ".#{version.patch}"
    end

    # The page has multiple identical links for each package (and seven for the common
    # headers), so we just pick the first of each.
    #
    kernel_page = open(kernel_page_address).read

    if kernel_page =~ /Build for #{ARCHITECTURE} succeeded/
      common_headers = kernel_page[/linux-headers-.+?_all\.deb/] || raise('common headers')
      specific_headers = kernel_page[/linux-headers-.+?-#{KERNEL_TYPE}_.+?_#{ARCHITECTURE}.deb/] || raise('spec. headers')
      image = kernel_page[/linux-image-.+?-#{KERNEL_TYPE}.+?_#{ARCHITECTURE}.deb/] || raise('image')


      package_addresses = [
        "#{kernel_page_address}/#{common_headers}",
        "#{kernel_page_address}/#{specific_headers}",
        "#{kernel_page_address}/#{image}"
      ]

      if version >= KernelVersion.new(4, 16, 4)
        modules = kernel_page[/linux-modules-.+?-#{KERNEL_TYPE}.+?_#{ARCHITECTURE}.deb/] || raise('modules')
        package_addresses << "#{kernel_page_address}/#{modules}"
      end

      package_addresses
    else
      []
    end
  end

  def download_package_files(package_addresses, destination_directory)
    package_addresses.map do |package_address|
      file_basename = File.basename(package_address)
      destination_file = File.join(destination_directory, file_basename)

      DownloadWithProgress.new.execute(package_address, destination_file)

      destination_file
    end
  end

  def install_packages(package_files)
    escaped_files_list = package_files.map { |filename| filename.shellescape }.join(' ')
    `sudo dpkg -i #{escaped_files_list}`
  end

end

# The web page link, architecture, and kernel type, all have a default.
#
if __FILE__ == $PROGRAM_NAME

  long_help = <<~HELP
    When the user specifies --install, if the patch version is not specified, the latest <major.minor> kernel version is installed.
  HELP

  options = SimpleScripting::Argv.decode(
    ['-i', '--install VERSION', 'Install a certain version [format: <maj.min[.patch]>]'],
    ['-s', '--store-path PATH', 'Store packages to path (default: /tmp)'],
    long_help: long_help,
  ) || exit

  UpdateMainlineKernel.new.execute(options)

end
