#!/usr/bin/env bash

set -o pipefail
set -o errexit
set -o nounset
set -o errtrace
shopt -s inherit_errexit

c_repo_address=https://github.com/bluez/bluez.git
c_temporary_dir=$(mktemp -d --suffix=.bluez)
c_help="Usage: $(basename "$0") [-h|--help] [-v|--version VERSION]

Upgrade Bluez from source.

Needs to be run as root.

Uninstalls the files corresponding to the previous, and puts the bluez package on hold.

If the current version is the latest (or the specified version), nothing is done."

v_version=

function decode_cmdline_args {
  local params
  params=$(getopt --options hv: --long help,version: --name "$(basename "$0")" -- "$@")

  eval set -- "$params"

  while true; do
    case $1 in
      -h|--help)
        echo "$c_help"
        exit 0 ;;
      -v|--version)
        v_version=$2
        shift 2 ;;
      --)
        shift
        break ;;
    esac
  done

  if [[ $# -ne 0 ]]; then
    echo "$c_help"
    exit 1
  fi
}

function check_user {
  if [[ $EUID -ne 0 ]]; then
    >&2 echo "The script needs to be run as root"
    exit 1
  fi
}

function register_exit_hook {
  function _exit_hook { rm -rf "$c_temporary_dir"; }
  trap _exit_hook EXIT
}

function clone_repository {
  git clone "$c_repo_address" "$c_temporary_dir"
}

function switch_dir {
  cd "$c_temporary_dir"
}

# Format: X.YZ
#
function find_current_version {
  bluetoothd --version
}

# Format: X.YZ
#
function find_latest_version {
  git ls-remote "$c_repo_address" \
    | perl -lne 'print $1 if /refs\/tags\/([\d.]+)$/' \
    | sort -V \
    | tail -n 1
}

function change_to_version {
  local version=$1

  git checkout "$version"
}

function find_bluez_libexecdir {
  dpkg -L bluez | perl -ne 'print $1 if /(\/usr\/lib.*)\/bluetooth$/'
}

function clean_and_configure {
  local libexecdir=$1

  git clean -fdx

  ./bootstrap
  ./configure \
    --prefix=/usr --mandir=/usr/share/man --sysconfdir=/etc --localstatedir=/var \
    --libexecdir="$libexecdir"
}

function uninstall {
  make uninstall
}

function build_project {
  make -j "$(nproc)"
}

function install {
  # The file `/usr/lib/cups/backend/bluetooth` is also owned by the `bluez-cups` package; it's not clear
  # if it needs to be up to date, but if one doesn't use it, it doesn't matter.
  # In theory, `--disable-cups` can be used, but it causes a configure error (not mentioned by the documentation).
  #
  make install
}

function restart_bluetooth_service {
  systemctl daemon-reload
  systemctl restart bluetooth
}

function hold_bluez_package {
  apt-mark hold bluez
}

function main {
  register_exit_hook

  check_user

  current_version=$(find_current_version)

  local target_version
  target_version=${v_version:-$(find_latest_version)}

  if [[ $current_version != "$target_version" ]]; then
    clone_repository "$current_version"
    switch_dir

    change_to_version "$current_version"

    # The location changed between Ubuntu 22.04 and 24.04.
    #
    local libexecdir
    libexecdir=$(find_bluez_libexecdir)

    clean_and_configure "$libexecdir"

    uninstall

    change_to_version "$target_version"

    clean_and_configure "$libexecdir"

    build_project

    install

    restart_bluetooth_service

    hold_bluez_package

    echo "Upgraded Bluez to v$target_version."
  else
    echo 'Bluez already at the target version.'
  fi
}

decode_cmdline_args "$@"
main
