#!/usr/bin/env bash

set -o pipefail
set -o errexit
set -o nounset
set -o errtrace
shopt -s inherit_errexit

c_repo_address=https://github.com/bluez/bluez.git
c_temporary_dir=$(mktemp -d --suffix=.bluez)
c_help="Usage: $(basename "$0") [-r|--repository-dir <dir>] [-h|--help]

Upgrade Bluez from source.

Uninstalles the files corresponding to the previous, and puts the bluez package on hold.

If the current version is the latest, nothing is done."

v_repository_dir=

function decode_cmdline_args {
  local params
  params=$(getopt --options hr: --long help,repository-dir: --name "$(basename "$0")" -- "$@")

  eval set -- "$params"

  while true; do
    case $1 in
      -h|--help)
        echo "$c_help"
        exit 0 ;;
      -r|--repository-dir)
        v_repository_dir=$2
        shift 2 ;;
      --)
        shift
        break ;;
    esac
  done

  if [[ $# -ne 0 ]]; then
    echo "$c_help"
    exit 1
  fi

  if [[ -z $v_repository_dir ]]; then
    v_repository_dir=$c_temporary_dir
  fi
}

function register_exit_hook {
  function _exit_hook { rm -rf "$c_repo_address"; }
  trap _exit_hook EXIT
}

function cache_sudo {
  sudo -v
}

function clone_repository {
  git clone "$c_repo_address" "$c_temporary_dir"
}

function switch_dir {
  cd "$v_repository_dir"
}

function clean_repository {
  rm -f .gitignore
  git clean -fd
  git checkout .gitignore
}

function fetch_repository {
  git fetch
}

# Format: X.YZ
#
function find_current_version {
  bluetoothd --version
}

# Format: X.YZ
#
function find_latest_version {
  git ls-remote "$c_repo_address" \
    | perl -lne 'print $1 if /refs\/tags\/([\d.]+)$/' \
    | sort -V \
    | tail -n 1
}

function change_to_version {
  local version=$1

  git checkout "$version"
}

function find_bluez_libexecdir {
  dpkg -L bluez | perl -ne 'print $1 if /(\/usr\/lib.*)\/bluetooth$/'
}

function clean_and_configure {
  local libexecdir=$1

  git clean -fdx

  ./bootstrap
  ./configure \
    --prefix=/usr --mandir=/usr/share/man --sysconfdir=/etc --localstatedir=/var \
    --libexecdir="$libexecdir"
}

function uninstall {
  sudo make uninstall
}

function build_and_install {
  make -j "$(nproc)"

  # The file `/usr/lib/cups/backend/bluetooth` is also owned by the `bluez-cups` package; it's not clear
  # if it needs to be up to date, but if one doesn't use it, it doesn't matter.
  # In theory, `--disable-cups` can be used, but it causes a configure error (not mentioned by the documentation).
  #
  sudo make install
}

function restart_bluetooth_service {
  sudo systemctl daemon-reload
  sudo systemctl restart bluetooth
}

function hold_bluez_package {
  sudo apt-mark hold bluez
}

function main {
  register_exit_hook

  current_version=$(find_current_version)
  latest_version=$(find_latest_version)

  if [[ $current_version != "$latest_version" ]]; then
    cache_sudo

    if [[ $v_repository_dir == "$c_temporary_dir" ]]; then
      clone_repository "$current_version"
      switch_dir
    else
      switch_dir
      clean_repository
      fetch_repository
    fi

    change_to_version "$current_version"

    # The location changed between Ubuntu 22.04 and 24.04.
    #
    local libexecdir
    libexecdir=$(find_bluez_libexecdir)

    clean_and_configure "$libexecdir"

    uninstall

    change_to_version "$latest_version"

    clean_and_configure "$libexecdir"

    build_and_install

    restart_bluetooth_service

    hold_bluez_package

    echo "Upgraded to v$latest_version."
  else
    echo 'Already at the latest version.'
  fi
}

decode_cmdline_args "$@"
main
