#!/usr/bin/env bash

set -o pipefail
set -o errexit
set -o nounset
set -o errtrace
shopt -s inherit_errexit

c_model=large # as of Aug/2025, maps to `large-v3`
c_help="Usage: $(basename "$0") [-h|--help] [-s|--srt] [-e|--english] [-i|--italian] <input> {<input2>...}"

v_output_format=txt
v_inputs=
v_english_input=      # boolean; false: blank, true: anything else
v_italian_input=      # boolean; false: blank, true: anything else

function decode_cmdline_args {
  local params
  params=$(getopt --options hsei --long help,srt,english,italian --name "$(basename "$0")" -- "$@")

  eval set -- "$params"

  while true; do
    case $1 in
      -h|--help)
        echo "$c_help"
        exit 0 ;;
      -s|--srt)
        v_output_format=srt
        shift ;;
      -e|--english)
        v_english_input=1
        shift ;;
      -i|--italian)
        v_italian_input=1
        shift ;;
      --)
        shift
        break ;;
    esac
  done

  if [[ $# -lt 1 ]]; then
    echo "$c_help"
    exit 1
  elif [[ -n $v_english_input && -n $v_italian_input ]]; then
    echo "EN<>IT are mutually exclusive"
    exit 1
  fi

  v_inputs=("$@")
}

function set_device {
  declare -x device_out=$1

  if [[ $(uname) == Darwin ]]; then
    device_out=mps
  else
    device_out=cpu
  fi
}

# In order to list the most recent models (they are not in the repo help), use:
#
#   python -c "import whisper; print(whisper._MODELS.keys())"
#
function main {
  local device

  set_device device

  local options=(
    --model "$c_model"
    --device "$device"
    --output_format "$v_output_format"
  )

  if [[ -n $v_english_input ]]; then
    options+=(--language en)
  elif [[ -n $v_italian_input ]]; then
    options+=(--language it)
  fi

  for input in "${v_inputs[@]}"; do
    whisper "${options[@]}" "$input"
  done
}

decode_cmdline_args "$@"
main
