#!/usr/bin/env bash

set -o pipefail
set -o errexit
set -o nounset
set -o errtrace
shopt -s inherit_errexit

c_help="Usage: $(basename "$0") [-h|--help] <arg>"

function decode_cmdline_args {
  local params
  params=$(getopt --options h --long help --name "$(basename "$0")" -- "$@")

  eval set -- "$params"

  while true; do
    case $1 in
      -h|--help)
        echo "$c_help"
        exit 0 ;;
      --)
        shift
        break ;;
    esac
  done
}

function main {
  if [[ -n ${WSL_DISTRO_NAME:-} ]]; then
    # wslview causes an "interop disabled" series of errors, but it's confusing to fix it, so we just
    # filter the errors out, since opening the files works anyway.
    #
    wslview "$@" 2> /dev/null
  elif [[ $(uname) == "Darwin" ]]; then
    open "$@"
  else
    xdg-open "$@"
  fi
}

decode_cmdline_args "$@"
main "$@"
